git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    tag = "0.4.0",
)

load("@io_bazel_rules_go//go:def.bzl", "go_repositories")
load("@bazel_tools//tools/build_defs/docker:docker.bzl", "docker_build")

go_repositories()
