steps:
- name: 'bash'
  args: ['chmod', '-R', '777', '.']
# 1. Run as the container's default user, but use bash to fix permissions first
- name: 'gcr.io/bazel-public/bazel:7.4.1'
  entrypoint: 'bash'
  dir: '/workspace'
  args:
    - '-c'
    - |
      bazel --output_user_root=/tmp/bazel \
            build \
            --curses=no \
            gce-containers-startup
      cp -L bazel-bin/gce-containers-startup/gce-containers-startup_/gce-containers-startup docker/gce-containers-startup

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gce-containers/konlet:$BRANCH_NAME-HEAD', 'docker']
images: ['gcr.io/gce-containers/konlet:$BRANCH_NAME-HEAD']
