#!/bin/bash

# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

readonly GET_METADATA_VALUE='/usr/share/google/get_metadata_value'
readonly KONLET_VERSION_TAG='v.0.11-latest'

SPEC=$(${GET_METADATA_VALUE} 'attributes/gce-container-declaration')
if [[ $? -ne 0 ]]; then
  echo 'No metadata present - not running containers'
  exit 0
fi

# Make sure that Docker events collector is running for Konlet (only if the
# metadata is present).
systemctl start docker-events-collector.service

ACTUAL_KONLET_VERSION=$(${GET_METADATA_VALUE} 'attributes/gce-container-runner-version-override')
if [[ $? -ne 0 ]]; then
  ACTUAL_KONLET_VERSION="${KONLET_VERSION_TAG}"
fi

docker run --rm --privileged \
  --log-driver=json-file \
  --net="host" \
  -v=/var/run/docker.sock:/var/run/docker.sock \
  -v=/etc/profile.d:/host/etc/profile.d \
  -v=/dev:/dev \
  -v=/mnt:/mnt \
  -v=/proc:/host_proc \
  "gcr.io/gce-containers/konlet:${ACTUAL_KONLET_VERSION}"

